### ISSUE TITLE
Support for asynchronous tasks

### ISSUE THREAD

**Issue by mderriey** [cake-build/frosting#45]
Hi there,

I've been using Frosting lately and am very happy with it, thanks for the top-notch work!

With Cake [recently supporting asynchronous tasks](https://cakebuild.net/blog/2017/10/cake-v0.23.0-released#asynchronous-tasks), I was wondering if this would be something we could think about _baking into_ Frosting.

I'd be very happy to contribute if you could provide some guidance on how to achieve this. For the moment, I'll have a look at how it's built right now.

Thanks again for the :100: work!

**Comment by patriksvensson** [comment]
@mderriey Thank you very much for the nice words! ❤️ 

Asynchronous tasks would absolutely be possible now with Frosting since it's available in Cake.
You are more than welcome adding support for this.

I don't have any suggestions per se for now except that we would like to keep the synchronous alternatives to not break backwards compatibility. Other than that, I have no objection to making the whole "pipeline" asynchronous.

Let me know if you want any more information or suggestions and I will try doing my best answering them.
